version: '3.8'

services:
  scrapping:
    image: alesantos175/scrapping:5.0
    networks:
      - traefik_public
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_public"
        - "traefik.http.routers.scrapping.rule=Host(`scrapping.apsolutions.ia.br`)"
        - "traefik.http.routers.scrapping.entrypoints=websecure"
        - "traefik.http.routers.scrapping.tls=true"
        - "traefik.http.routers.scrapping.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.scrapping.loadbalancer.server.port=80"
        - "traefik.http.services.scrapping.loadbalancer.healthcheck.path=/health"
        - "traefik.http.services.scrapping.loadbalancer.healthcheck.interval=30s"
    # IMPORTANTE: Aumentar memória compartilhada para o Chromium
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 2147483648  # 2GB

networks:
  traefik_public:
    external: true